### ISSUE TITLE
Support multiple jobs on the same node

### ISSUE THREAD

**Issue by stephenlienharrell** [TACC/tacc_stats#41] opened 2023-06-13 15:54 UTC
Currently we collect everything at a node-level. We need to examine what metrics can be split out (on a core or socket basis) and what is not able to be split out and if that is useful.

**Comment by stephenlienharrell** [comment] 2023-06-20 15:57
for CPU
need core-affinity matched to job id

For Memory:
Need to find all memory usage from primary job starter programmatically. Find job starter, then get all child process memory:  ps -o pid,ppid,pgid,comm,%cpu,%me

Snapshot this at the same time as the rest of the metrics - find out if there is a way to get the job id, then match jobid to specific processes on-node to get snapshot of memory usage.

Can we do this programmatically for any other statistics?

**Comment by sanga1999** [comment] 2024-08-20 15:37
Duplicate of #46

**Closed by sanga1999** 2024-08-20 15:37 UTC
